TRAIN:
  WARMUP_EPOCHS: 5
  EPOCHS: 300
  BASE_LR: 2e-4
  WEIGHT_DECAY: 0.03
  OPTIMIZER: adamw
DATA:
  # BATCH_SIZE: 4096
AUG:
  SSL_AUG: True
  SSL_AUG_TYPE: byol
MODEL:
  TYPE: byol
  ENCODER: vit_small
  NAME: byol__vit_small__odpr0_tdpr0_stopgradconv1_cm0996_proj2_pred2
  SSL:
    ENCODER: vit_small
    #ONLINE_DROP_PATH_RATE: 0.2
    #TARGET_DROP_PATH_RATE: 0.0
    CONTRAST_MOMENTUM: 0.996
    PROJ_NUM_LAYERS: 2
    PRED_NUM_LAYERS: 2
    SSL.STOP_GRAD_CONV1: True