TRAIN:
  WARMUP_EPOCHS: 5
  EPOCHS: 300
  BASE_LR: 2e-4
  WEIGHT_DECAY: 0.03
  OPTIMIZER: 
    NAME: adamw
#DATA:
  # BATCH_SIZE: 4096
AUG:
  SSL_AUG: True
  SSL_AUG_TYPE: byol
MODEL:
  TYPE: byol
  ENCODER: swin_tiny
  NAME: byol__swin_tiny__odpr0_tdpr0_cm0996_proj2_pred2
  #ONLINE_DROP_PATH_RATE: 0.2
  #TARGET_DROP_PATH_RATE: 0.0
  CONTRAST_MOMENTUM: 0.996
  PROJ_NUM_LAYERS: 2
  PRED_NUM_LAYERS: 2