TRAIN:
  WARMUP_EPOCHS: 10
  EPOCHS: 300
  BASE_LR: 0.4
  WEIGHT_DECAY: 1e-6
  OPTIMIZER: 
    NAME: lars
    TRUST_COEFFICIENT: 1e-3
#DATA:
  # BATCH_SIZE: 4096
AUG:
  SSL_AUG: True
  SSL_AUG_TYPE: byol
MODEL:
  TYPE: byol
  ENCODER: resnet50
  NAME: byol__resnet50__cm0996_proj2_pred2
  CONTRAST_MOMENTUM: 0.996
  PROJ_NUM_LAYERS: 2
  PRED_NUM_LAYERS: 2