TRAIN:
  WARMUP_EPOCHS: 5
  EPOCHS: 300
  BASE_LR: 0.001
  WEIGHT_DECAY: 0.05
  OPTIMIZER: adamw
DATA:
  # BATCH_SIZE: 512
AUG:
  SSL_AUG: True
  SSL_AUG_TYPE: byol
MODEL:
  TYPE: synco
  ENCODER: vit_small
  NAME: synco__vit_small__odpr02_tdpr0_cm099_ct02_queue4096_proj2_pred2
  SSL:
    ENCODER: vit_small
    ONLINE_DROP_PATH_RATE: 0.05
    TARGET_DROP_PATH_RATE: 0.0
    CONTRAST_MOMENTUM: 0.99
    CONTRAST_TEMPERATURE: 0.2
    CONTRAST_NUM_NEGATIVE: 4096
    PROJ_NUM_LAYERS: 2
    PRED_NUM_LAYERS: 2
    N_HARD: 256
    N1: 128
    N2: 128
    N3: 128
    N4: 128
    N5: 128
    N6: 128
    WARMUP_EPOCHS: 30
    COOLDOWN_EPOCHS: 100